language: java

before_install:
  - git submodule update --init --recursive

script: ./bin/run_tests.sh

notifications:
  email:
    recipients:
      - greenbutton-dev@googlegroups.com
    on_success: change
